# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
platform_packages:
  - glibc-common
  - openldap
  - openldap-clients
  - openssl

iap_nodejs_package: "@nodejs:20"

python_version: 3.11
python_executable: "/usr/bin/python{{ python_version }}"
pip_executable: "/usr/bin/pip{{ python_version }}"

python_packages:
  - python3.11
  - python3.11-pip

base_python_dependencies:
  - pip
  - setuptools
  - wheel

app_python_dependencies:
  - jinja2==3.1.2
  - markupsafe==2.1.4
  - pymongo
  - textfsm==1.1.3

mongodb_version: 7.0

mongodb_tools_packages:
  - mongodb-database-tools
  - mongodb-mongosh

mongo_shell: mongosh

# For IAP release 16.0, the installation directory and the services directory are set in the RPM
# and therefore cannot be changed in the inventory
iap_install_dir: "/opt/itential/platform"
iap_services_dir: "{{ iap_install_dir }}/services"

platform_encrypt_pathprops: false
