# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
os_packages:
  - coreutils
  - openssl

os_security_packages:
  - checkpolicy
  - libselinux
  - libselinux-utils
  - policycoreutils
  - policycoreutils-python-utils
  - selinux-policy-mls

os_operational_packages:
  - bind-utils
  - curl
  - dos2unix
  - git
  - gzip
  - jq
  - man
  - rsyslog
  - sudo
  - sysstat
  - tar
  - tcpdump
  - telnet
  - unzip
  - wget
  - which
  - zip
